api_platform:
    title: ABC Training School Api
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    formats:
        jsonld:
            mime_types: ['application/ld+json']

        jsonapi: ['application/vnd.api+json']
        json: ['application/json']
        html: ['text/html']
        multipart:
            mime_types: ['multipart/form-data']
